# Generated by Django 3.0.7 on 2020-07-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesdb',
            name='category',
            field=models.CharField(default='Medium Article', max_length=300),
            preserve_default=False,
        ),
    ]
